project:
  type: website
  output-dir: docs

website:
  title: "Empolyee of The Month 2025"
  navbar:
    left:
      - href: index.qmd
        text: Beranda
      - href: qmd/00-tentang.qmd
        text: Tentang
      - href: qmd/01_alur.qmd
        text: Alur
      - href: qmd/misc/ssn2024_03/rls.qmd
        text: Rata-rata Lama Sekolah

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



