project:
  type: website
  output-dir: docs

website:
  title: "Running Data Aja"
  navbar:
    left:
      - href: index.qmd
        text: Beranda
      - href: qmd/04-olah-data-stata-r.qmd
        text: "Belajar Dikit"
      - href: qmd/indeks-pembangunan-pemuda-daerah.qmd
        text: "SUSENAS"
      - href: qmd/olah-data-sakernas.qmd
        text: "SAKERNAS"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



