project:
  type: website
  output-dir: docs

website:
  title: "Empolyee of The Month 2025"
  navbar:
    left:
      - href: index.qmd
        text: Beranda
      - href: 00-tentang.qmd
        text: Tentang
      - href: 01-januari.qmd
        text: Januari
      - href: 02-februari.qmd
        text: Februari
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



